@startuml

interface IRecordRepository{
 + GetByDoctorIdPerDay(doctorId): Task<List<RecordListDoctorDto>>
}
class BaseRepository<T, K>

class RecordRepository {
 + GetByDoctorIdPerDay(doctorId): Task<List<RecordListDoctorDto>>
}

class GetListRecordByDoctor {
  - _recordRepository: IRecordRepository
  +ExecuteAsync(int doctorId): Task<ApiResponse<List<RecordListDoctorDto>, List<string>>>
}


class RecordController {
  - _changeRecordStatusUseCase: ChangeRecordStatusUseCase
  + ChangeRecordStatus(int recordId): Task<IActionResult>
}



BaseRepository <|-- RecordRepository
IRecordRepository <|.. RecordRepository
IRecordRepository <.. GetListRecordByDoctor
RecordController ..> GetListRecordByDoctor

@enduml