@startuml

interface IRecordRepository{
 + GetByDoctorIdPerDay(doctorId): Task<List<RecordListDoctorDto>>
}
class RecordRepository {
 + GetByDoctorIdPerDay(doctorId): Task<List<RecordListDoctorDto>>
}

class GetListRecordByDoctor {
  - _recordRepository: IRecordRepository
  +ExecuteAsync(int doctorId): Task<ApiResponse<List<RecordListDoctorDto>, List<string>>>
}


class RecordController {
  - _getListRecordByDoctor: GetListRecordByDoctor
  +  GetListRecordByDoctor(): Task<IActionResult>
}

class RecordListDoctorDto{
+ Id: int
+ PatientName: string
+ DoctorName: string
+ ExportId: int
+ Diagnostic: string
+ Reason: string
+ Status: RecordStatusEnum
+ StartAt: DateTime
+ EndAt: DateTime
+ IsReVisit: bool
}

GetListRecordByDoctor ..> RecordListDoctorDto
IRecordRepository <|.. RecordRepository
IRecordRepository <.. GetListRecordByDoctor
RecordController ..> GetListRecordByDoctor

@enduml