@startuml
header : giangmn
title: Update Supplier
autonumber

actor "Actor" as a
participant "Web FE" as fe
participant "Web BE" as be
database "Database" as db

a-> fe: Request update Supplier
fe ++
fe -> be: Request update Supplier
be++
be -> be: Validate request
alt Validate fail
be -->> fe: Return fail message
fe -->> a: Return fail message

end

be -> db: Query get Supplier if Supplier is existed
db++
db --> be: return result
db--
alt Patient isn't existed
be -->> fe: Return fail message
fe -->> a: Return fail message
end
be->db: update Supplier information
db++
db--> be: return result
db--
be --> fe: return result
be--
fe--> a: return result
fe--
@enduml