@startuml
header : giangmn
title: Change Password Patient
autonumber

participant "Web FE" as fe
participant "Web BE" as be
participant "Database" as db

fe -> be: Request change password
be++
be -> be: Validate request
alt Validate fail
be -->> fe: Return fail message
end
be -> db: Query get patient
db++
db --> be: return result
db--
alt Patient not found/ Query fail
be -->> fe: Return fail message
end

be-> be: change password information
be++

alt Password validate fail
be -->> fe: Return fail message
be--
end
be --> fe: return result
be--
@enduml