@startuml
header : giangmn
title: Change Password Patient
autonumber

actor "Actor" as a
participant "Web FE" as fe
participant "Web BE" as be
database "Database" as db

a->fe : Request change password
fe++
fe -> be: Request change password
be++
be -> be: Validate request
alt Validate fail
be -->> fe: Return fail message
fe-->>a: Show fail message
end
be -> db: Query get patient
db++
db --> be: return result
db--
alt Patient not found/ Query fail
be -->> fe: Return fail message
fe-->>a: Show fail message
end

be-> be: change password information
be++
be--

alt Password validate fail
be -->> fe: Return fail message
fe-->>a: Show fail message
end

be->db: Change password
db++
db->be: return result
db--
be --> fe: return result
be--
fe->a: return result
fe--
@enduml