@startuml
header : giangmn
title: Create Patient
autonumber

participant "Web FE" as fe
participant "Web BE" as be
participant "Database" as db
participant "Email Service" as es

fe -> be: Request create Patient
be++
be -> be: Validate request
alt Validate fail
be -->> fe: Return fail message
end

be -> db: insert new patient
db++
db --> be: return result
db--
alt fail create patient
be -->> fe: Return fail message
end
alt Created Patient has Email
be -> es: Call send mail service
es++
es->es :Send password to User's mail
es++
es--
es--
end
be --> fe: return result
be--

@enduml