@startuml
header : giangmn
title: Create Patient
autonumber

actor "Actor" as a
participant "Web FE" as fe
participant "Web BE" as be
database "Database" as db
participant "Email Service" as es

a->fe : Request create Patient
fe++
fe -> be: Request create Patient
be++
be -> be: _validator.ValidateAndThrow()
alt Validate fail
be -->> fe: Return fail message
fe-->> a: Show fail message
end

be -> db: _patientRepository.Add();
db++
db --> be: return result
db--
alt fail create patient
be -->> fe: Return fail message
fe-->> a: Show fail message

end
alt Created Patient has Email
be -> es: Call send mail service
es++
es->es : _emailService.SendEmailAsync()
es++
es--
es--
end
be --> fe: return result
fe--> a: return result
fe--
be--

@enduml