@startuml
header : giangmn
title: Update Patient
autonumber

actor "Actor" as a
participant "Web FE" as fe
participant "Web BE" as be
participant "Database" as db

a->fe : Request update Patient
fe++
fe -> be: Request update Patient
be++
be -> be: _validator.ValidateAndThrow()
alt Validate fail
be -->> fe: Return fail message
fe -->> a: Show fail message
end

be -> db: _patientRepository.GetPatientByIdAsync()
db++
db --> be: return result
db--
alt Patient isn't existed
be -->> fe: Return fail message
fe -->> a: Show fail message

end
be->db: update Patient information (_unitOfWork.SaveChangesAsync())
db++
db--> be: return result
db--
be --> fe: return result
be--
fe -->> a: return result
fe--
@enduml