@startuml
header : giangmn
title: Get Patient List
autonumber

actor "Actor" as a
participant "Web FE" as fe
participant "Web BE" as be
participant "Database" as db

a-> fe: Request get Patient List
fe++
fe -> be: Request get Patient List
be++
be -> be: Validate request
alt Validate fail
be -->> fe: Return fail message
fe -->> a: Return fail message
end

be -> db: _patientRepository.GetAllAsync()
db++
db --> be: return result
db--
be --> fe: return result
be--
fe --> a: return result
fe--
@enduml