@startuml
header : giangmn
title: Get List Record (Queue)
autonumber

participant "Web FE" as fe
participant "Web BE" as be
participant "Database" as db

fe -> be: Request get Record List
be++
be -> db: Query get all patient list
db++
db --> be: return result
db--
alt Record is empty
be -->> fe: Return not available message
end
be --> fe: return result
@enduml