@startuml
header : giangmn
title: Create Supplier
autonumber

participant "Web FE" as fe
participant "Web BE" as be
participant "Database" as db

fe -> be: Request create Supplier
be++
be -> be: Validate request
alt Validate fail
be -->> fe: Return fail message
end

be -> db: insert new Supplier
db++
db --> be: return result
db--
be --> fe: return result
be--

@enduml