@startuml
header : giangmn
title: Get all Supplier
autonumber

participant "Web FE" as fe
participant "Web BE" as be
participant "Database" as db

fe -> be: Request get all Supplier
be++
be -> be: Validate request
alt Validate fail
be -->> fe: Return fail message
end

be -> db: Query get all Supplier
db++
db --> be: return result
db--
be --> fe: return result
@enduml