@startuml
interface IPatientRepository
interface IUnitOfWork

class BaseRepository<T, K>

class PatientRepository {
}

  class ChangePatientPassword {
    -  _patientRepository: IPatientRepository
      - _unitOfWork: IUnitOfWork
      - _validator: IValidator<ChangePasswordRequest>
  + ChangePatientPassword(..Request request, int patientId): Task<ApiResponse<List<string>, List<string>>>
  }

class ChangePasswordValidator {
  + ChangePasswordValidator()
}

class PatientController {
  - _createPatient: ChangePatientPassword
  + ChangePassword(ChangePasswordRequest request): Task<IActionResult>
}

class ChangePasswordRequest {
  +  OldPassword: string
  +  NewPassword: string
  +  ConfirmPassword: string
}

BaseRepository <|-- PatientRepository
IPatientRepository <|.. PatientRepository
IPatientRepository <.. ChangePatientPassword
IUnitOfWork <.. ChangePatientPassword


ChangePatientPassword ..> ChangePasswordRequest
PatientController ..> ChangePatientPassword
PatientController ..> ChangePasswordRequest
interface IValidator<T>
IValidator <|.. ChangePasswordValidator
IValidator <.. ChangePatientPassword
@enduml
