@startuml
interface IPatientRepository{
GetPatientByIdAsync(int patientId): Patient
}
interface IUnitOfWork

class PatientRepository {
GetPatientByIdAsync(int patientId): Patient
}

  class ChangePatientPassword {
    -  _patientRepository: IPatientRepository
      - _unitOfWork: IUnitOfWork
      - _validator: IValidator<ChangePasswordRequest>
  + ChangePatientPassword(..Request request, int patientId): Task<ApiResponse<List<string>, List<string>>>
  }

class ChangePasswordValidator {
  + ChangePasswordValidator()
}

class PatientController {
  - _changePassword: ChangePatientPassword
  + ChangePassword(ChangePasswordRequest request): Task<IActionResult>
}

class ChangePasswordRequest {
  +  OldPassword: string
  +  NewPassword: string
  +  ConfirmPassword: string
}

IPatientRepository <|.. PatientRepository
ChangePatientPassword ..> IPatientRepository

IUnitOfWork <.. ChangePatientPassword


ChangePatientPassword ..> ChangePasswordRequest
PatientController ..> ChangePatientPassword
PatientController ..> ChangePasswordRequest
interface IValidator<T>
IValidator <|.. ChangePasswordValidator
IValidator <.. ChangePatientPassword
@enduml
