@startuml
interface IPatientRepository{
+GetPatientByIdAsync(int patientId): Patient
+FindPatientByPhoneAndMailAsync(string phone, string email): List<Patient>
}
interface IValidator<T>
interface IUnitOfWork

class PatientRepository {
+GetPatientByIdAsync(int patientId): Patient
+FindPatientByPhoneAndMailAsync(string phone, string email): List<Patient>
}

class UpdatePatientUseCase {
  -  _patientRepository: IPatientRepository
  -  _unitOfWork: IUnitOfWork
  -  _validator: IValidator<UpdatePatientRequest>
  +UpdatePatientAsync(UpdatePatientRequest request, int patientId)
}

class UpdatePatientValidator {
  + UpdatePatientValidator()
}

class PatientController {
  -  _createPatient: CreatePatientUseCase
  + CreateAsync(UpdatePatientRequest request): Task<IActionResult>
}

class UpdatePatientRequest {
  +  Name: string
  +  Email: string
  +  Phone: string
  +  Birthday: DateTime
}

IPatientRepository <|.. PatientRepository
IPatientRepository <.. UpdatePatientUseCase
IUnitOfWork <.. UpdatePatientUseCase
IValidator <|.. UpdatePatientValidator
IValidator <.. UpdatePatientUseCase

UpdatePatientUseCase ..> UpdatePatientRequest
PatientController ..> UpdatePatientUseCase
PatientController ..> UpdatePatientRequest

@enduml
