@startuml
interface IPatientRepository{
GetPatientByIdAsync(int patientId): Patient
}

class PatientRepository {
GetPatientByIdAsync(int patientId): Patient
}

class ViewPatientProfileUseCase {
  -  _patientRepository: IPatientRepository
+ ViewProfileAsync(int patientId): Task<ApiResponse<ViewPatientProfileResponse, List<string>>>
}


class PatientController {
  -  _viewProfile: ViewPatientProfileUseCase
  +  Task<IActionResult>: ViewProfileAsync(int patientId)
}

class ViewPatientProfileResponse{
+  Name: string
+  Email: string
+  Phone: string
+  BirthDay: DateTime
}
IPatientRepository <|.. PatientRepository
IPatientRepository <.. ViewPatientProfileUseCase

PatientController ..> ViewPatientProfileUseCase
ViewPatientProfileUseCase ..> ViewPatientProfileResponse

@enduml
