@startuml
class BaseEntity<TId>{
+ Id: TId
+ CreateAt: DateTime
+ UpdateAt: DateTime
+ CreateBy: int
+ UpdateBy: int
}


class Patient                {
  + string? Name
  + string? Email
  + string? Password
  + string? Phone
  + DateTime? Birthday
  + bool IsUseGenPassword
  + virtual ICollection<Schedule> Schedules
  + virtual ICollection<Record> Records
}
BaseEntity <|-- Patient

Patient "1" o-- "many" Schedule
Patient "1" o-- "many" Record

enum StatusScheduleEnum
{
    Pending
    Confirmed
    Done
    Cancel
}
@enduml
