@startuml
header : giangmn
title: Create User
autonumber

actor "Actor" as a
participant "Web FE" as fe
participant "Web BE" as be
database "Database" as db
participant "Email Service" as es

a->fe : Request create User
fe++
fe -> be: Request create User
be++
be -> be: Validate request
alt Validate fail
be -->> fe: Return fail message
fe-->> a: Show fail message
end

be -> db: insert new User
db++
db --> be: return result
db--
alt fail create User
be -->> fe: Return fail message
fe-->> a: Show fail message

end
alt Created User has Email
be -> es: Call send mail service
es++
es->es :Send password to User's mail
es++
es--
es--
end
be --> fe: return result
fe--> a: return result
fe--
be--

@enduml